### ISSUE TITLE
Database module tracking issue

### ISSUE THREAD

**Issue by spacekookie** [qaul/qaul.net#215]
This is a tracking issue to document progress on the new database module :wink: 

- [ ] Create a connection manager interface (private)
  - [ ] Pick a database and connection manager implementation
- [ ] Create query builder for specific tasks
- [ ] Store abstracted data in table structs
- [ ] Interface with libqaul internal structs

### Further scope
This also fixes #139 which will require a configuration module (`todo: create tracking issue`)
