### ISSUE TITLE
HTTP API and core application logic

### ISSUE THREAD

**Issue by MathJud** [qaul/qaul.net#236]
Write a new HTTP API in Rust which will allow interfacing with a web front-end.
Someone working on this project would be responsible for not only implementing
the API with `json:api` in Rust, but also some of the the underlying core components
of the `qaul.net` library for user and message management, working closely together
with the rest of the team.

## Milestones

- [ ] Implement HTTP API in Rust
  - [ ] Decide on the details of the HTTP API
  - [ ] Ensure compatibility with the new Web GUI
- [ ] Design & Implement message management
- [ ] Implement configuration management
