### ISSUE TITLE
[Tracking] Updating docs

### ISSUE THREAD

**Issue by spacekookie** [qaul/qaul.net#243]
This is a tracking issue for the current state of the documentation

- [ ] Contributer documentation (`docs/contrib`)
  - [x] Technical outline
  - [ ] Service API (**blocked**)
- [ ] User documentation (`docs/users`)
- [ ] Host documentation under `docs.qaul.net`
