### ISSUE TITLE
qaul.net web site

### ISSUE THREAD

**Issue by MathJud** [qaul/qaul.net#255]
qaul.net community web site with the following features:

- [x] responsive design
- [x] community editable -> via github 
- [x] multi-language
  - [x] LTR & RTL capable
  - [x] Community translatable
- [x] community communication
  - [x] Zulip chat
  - [x] Mailing-lists
  - [x] contact email
  - [x] IRC channel
- [x] Legal
  - [x] License CC-By 4.0 license
  - [x] GDPR notice
  - [x] code of conduct
- [x] pages / content
  - [x] features & screenshots
  - [x] download
- [x] Tutorial section
  - [x] Tutorial overview
  - [x] Tags
  - [x] example tutorials
- [x] Documentation on how to contribute to the web site

**Comment by MathJud** [comment]
The web site is currently under community review #269
