### ISSUE TITLE
Setup servers, services & web page

### ISSUE THREAD

**Issue by MathJud** [qaul/qaul.net#256]
- [x] community editable web site (see #255)
  - community review of web site (see #269 )
- [x] community communication possibilities
  - [x]  zulip group chat
  - [x] contact email address
- [x] CI/CD
  - [x] setup automated builds
  - [x] show build status in github

**Comment by MathJud** [comment]
Web site is finished and currently under community review: https://test.qaul.net
