### ISSUE TITLE
Develop HTML5 GUI with documentation

### ISSUE THREAD

**Issue by MathJud** [qaul/qaul.net#258]
Ember GUI

- [ ] 

Ember Tests

- [ ] All screens and interactions are testable

REST API

- [x] REST API Defined
- [ ] REST API Implemented in Ember

Documentation

- [ ] Functionality
- [ ] Translation
- [ ] REST API
