### ISSUE TITLE
Project-Overview & Community Charter

### ISSUE THREAD

**Issue by MathJud** [qaul/qaul.net#270]
Project overview

- [x] Create project milestones
- [x] Create Tracking issues for the buildup of qaul.net 2.0

Community Charter

- [x] Code of Conduct
- [x] Software License
- [x] Online Documentation (see #243)
  - [x] How to write Documentation
