### ISSUE TITLE
Testing Findings, January 14 2022 

### ISSUE THREAD

**Issue by MathJud** [qaul/qaul.net#290]
## General

Due to a bug in the time calculation when sending RPC messages to the GUI, libqaul crashed (see logs below).
This crash was not transparent to the user, as the UI was still working. This led to confusion.

* [x] Fix libqaul bug time calculation bug
  * libqaul crashed due to time.rs panic (duration became negative)
  * Polkadot had the same problem: https://github.com/paritytech/polkadot/issues/4096
  * [x] find safer way of using time calculations
  * #295 

## Better Testing Feedback

* [x] #291
* [x] Log libqaul within flutter and make it accessible for analyzation in futher tests.
  * e.g. library quick_log https://pub.dev/packages/quick_log
* [x] Create the functionality to send the logs via email to the developers.
* [x] Create the functionality to send device soft/hardware information via email to the developers.
* [x] #297
* [x] #298

## UI Improvements

* [x] Android: Make System back button working
* [x] Mobile: Portrait view: Add gesture sliding functionality between the taps
* [x] Feed View: make user icons clickable
* [x] User Account View: show connectivity option in view
  * Display IP addresses via which the user is reachable
* [x] #293
* [x] Display round trip time milliseconds on network view correctly.

## Further Development Suggestions

- Synchronize feed
- Make User Validation Interactive
  - Automatically exchange further more private information
  - Explain Idea behind it to the user
- Create anti-spam feature for feed messenger

----

## Logs

Libqaul Panic Log

```
flutter: sendRpc send 84 bytes
flutter: sendRpc success

thread '<unnamed>' panicked at 'overflow when subtracting durations', library/core/src/time.rs:940:31
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace

flutter: sendRpc send 84 bytes
 ERROR libqaul::rpc                    > "SendError(..)"
flutter: sendRpc success
```
