### ISSUE TITLE
Testing Findings, February 24 2022

### ISSUE THREAD

**Issue by MathJud** [qaul/qaul.net#319]
## Connectivity

- Routing
  - [x] #317
  - [x] #323

## UI Improvements

There were serveral detected improvements for the user interface

- [x] User Overview
  - [x] Order users in chat user selection according to their online status
  - [x] Make users in chat selected searchable 
  - [x] Make user list searchable
- [x] Notifications about new messages

## Further Development Suggestions

- mDNS on Android more reliable
- Closed Group Communication Options
  - #333 
  - #332 
- Routing Protocol Improvements
  - #318
