### ISSUE TITLE
Log libqaul rust errors to file

### ISSUE THREAD

**Issue by MathJud** [qaul/qaul.net#342]
Rust error logs should write rust errors to file, while continuing displaying configurable rust errors via console.
With the crate `multi_log` one can use simultaneously multiple loggers.

* Continue using `pretty_env_logger` for logging to console with the ability to configure the verbosity via environment variables.
  * the android version uses `android_logger` instead of `pretty_env_logger`
* Use `simplelog` 

The Log files should be enumerated and only the most recent 3 shall be kept.

## Tasks

- [x] Create mutliple loggers via `multi_log`
  - [x] Continue using `pretty_env_logger` for console output.
    - [x] On Android use `android_logger` instead of `pretty_env_logger`
  - [x] Log errors to file via `simplelog`. The file shall be written to the storage location.
- [x] On each start it shall start a new log file. only the last 3 log files shall be kept.
- [x] Enable/Disable logging to file via the RPC debug messages.

## References

* multi_log: https://crates.io/crates/multi_log
* simplelog: https://crates.io/crates/simplelog
* pretty_env_logger: https://crates.io/crates/pretty_env_logger
  * currently used logger
  * see file: `rust/libqaul/src/lib.rs`
* android_logger: https://crates.io/crates/android_logger
  * currently used logger for android.
  * see file: `rust/libqaul/src/lib.rs`
