### ISSUE TITLE
UI Fixes

### ISSUE THREAD

**Issue by MathJud** [qaul/qaul.net#355]
Login Screen

- [x] User name should be sendable by pressing the enter key too.
- [x] Fix Timeout Error when creating user

Tablet View

- [x] Content area is right aligned and moves to the right when widening the window, leaving an growing gap between the tab-bar on the left and the content area.

Chat Messenger

- [x] Show message sent/received status

Android

- [x] #360

**Comment by brenodt** [comment]
@MathJud regarding the tablet view, that would also apply to the desktop environment. Do you have any suggestions as to what sort of content could take advantage of the real state when in landscape mode?
We can then put a solution in place for both desktop and tablet.

**Comment by MathJud** [comment]
At the moment mainly the chat messenger, here a sketch from the UI development ![IMG20220702111109.jpg](https://user-images.githubusercontent.com/1871891/176994315-3f738ee9-b4a7-4f20-b274-e048aff525da.jpg)
