### ISSUE TITLE
Group Chat

### ISSUE THREAD

**Issue by MathJud** [qaul/qaul.net#357]
The chat messenger shall receive a group chat feature.

A chat group has the following things

* conversation ID (Libp2p PeerId)
* Name
* Administrators
  * In the future there shall be multiple administrators. For the time being we only have the group creator as their administrator.
* Group members
* Group state revision (ascending integer)

Administrators can

* invite new users
* remove users
* change group name

When the administrator invites a new group member, he sends the member an inivite message.
When the user accepted the group invite, the administrator sends the new group state to all users.
Whenever the state of the group changes (e.g. members are added or removed, name changes, etc.) a message with the new state is sent to all users.

Group members can

* accept/decline invitations
* send messages & files to the group
* leave the group

When a group member sends a message to the group, the message is sent to each group member individually.

Messages to the group need to be identifiable. (sender signature of message)

Only messages from group members are accepted for a group communication.

## TO Implement

- [x] create RPC protobuf messages
  * chat group create request
    * send name
  * chat group create response
    * retrieve group info: name & ID
  * invite/remove user
  * change name
  * send message to group
  * -> Upgrade the conversation state to contain all requirements for groups & direct communication at the same time.
- [x] create network protobuf messages
  * group state message
  * group invitation message
  * group invitation response
- [x] Implement qaul-cli UI
- [x] Implement group administration
- [x] Implement message sending
