### ISSUE TITLE
Update Mechanism

### ISSUE THREAD

**Issue by MathJud** [qaul/qaul.net#374]
Create the foundations to create update mechanisms that break the storage or configuration scheme.

This shall be done by having a version number stored on the system that describes the version of the last run qaul application. The current executable can check if this version is compatible or if an update mechnism needs to be triggered.

## TODO

- [x] create configuration file that stores version number
- [x] create update module
  - [x] read the version configuration file before anything else

**Comment by MathJud** [comment]
closed by #458
