### ISSUE TITLE
UI Issues & Discussion

### ISSUE THREAD

**Issue by MathJud** [qaul/qaul.net#381]
Chat View

* Message Confirmation
  - [ ] It would be nice to have the check marks within the bubble
  - [ ] There should be two check marks: 1st for sent, 2nd for received.
* Invite messages
  - [ ] they should appear as special status messages, not from a user but in the center of the screen in a colourless grey/darker rendered field.
* Group Icon

Avatars

- [ ] consistent avatars in chat icon view and chat header (at the moment there is only one letter in the chat message area)
- [ ] Use only one letter, if there is only one word, only use one letter in the avatar.

**Comment by brenodt** [comment]
Tracking this issue over #394 .
