### ISSUE TITLE
User Referencing in Messaging

### ISSUE THREAD

**Issue by MathJud** [qaul/qaul.net#487]
There should be a way to reference users in messaging (suggested in #482 ).

In order to be able to identify and preview a user the following data is needed for it:

* qaul user ID
* user name (the user name is needed, if someone does not know the user yet)

The user could then be shown with a small coloured user avatar and the user name, directly linking to the user profile (if the user is known already).

Tasks

- [ ] Create User Markdown Format
- [ ] Render a referenced user
- [ ] WYSIWYG user referencing
  * select possible users after using the @
  * show user reference preview
