### ISSUE TITLE
Message Formatting

### ISSUE THREAD

**Issue by MathJud** [qaul/qaul.net#488]
There is already some very basic markdown formatting in the Chat Messaging (not yet in the public messaging).
¸*bold*¸ ¸_italic_¸ and URLs get rendered as links automatically.

There should be better message formatting options:

Formatting

- [ ] Append basic markdown formatting to public messages
- [ ] WYSIWYG editing of messages
  - [ ] Autoconvert formatted Text in the Editor
  - [ ] Add some formatting elements

Extended Markdown Elements

- [ ] #487

**Comment by alensiljak** [comment]
Please consider also the following use case: I need to transfer plain text from a phone to a pc (or vice versa). I'd like it to keep the original formatting as much as possible (spaces, tabs, underscores, etc.).
Right now, the messages sent through qaul are unreliable. The formatting changes the appearance, i.e. the underscores are gone and some text becomes italic.
~Also, there is no way for the end user to copy the message text. I will add this as a separate request, in fact.~ #486 

I thought that the basic Markdown rules apply, so I tried putting text in ``` but that did not change anything.
It would be beneficial to be able to ~see~ copy the plain text version of whatever was sent.
On the other hand, I like Markdown for easy formatting although I never actually use it in messaging applications.

Edit: In fact, if Copy Text option copies the underlying source content, then it does not really matter what the display formatting on the receiving end is. At least for this use case.
I guess that implementing the message copy function will resolve this.
