### ISSUE TITLE
Chat Messaging

### ISSUE THREAD

**Issue by MathJud** [qaul/qaul.net#489]
- [ ] #488 
- [ ] Send voice messages
- [ ] Send location
- [ ] Social Reactions: React with Emoticons on Messages
- [ ] Show message preview for long messages
- [ ] #486 
- [ ] #485
