### ISSUE TITLE
Public Message View Options

### ISSUE THREAD

**Issue by MathJud** [qaul/qaul.net#490]
Select which messages are being shown:

- [ ] Show messages by hashtag
- [ ] Only show messages of trusted users
- [ ] Don't show messages of blocked users
- [ ] Search messages
