### ISSUE TITLE
Public Messaging

### ISSUE THREAD

**Issue by MathJud** [qaul/qaul.net#491]
- [ ] #488 
- [ ] #490
- [ ] Show message preview of long messages
- [ ] Show message details
- [ ] React on messages

**Comment by Jadhav-Dhanashri** [comment]
Hello maintainers,
I'm new to freifunk.net open source contributions & excited to get started. I would like to work on this issue, & I'll follow the contribution guidelines carefully. Could you please assign it to me if it's available?
Thank you!
