### ISSUE TITLE
create qauld-ctl to control qauld

### ISSUE THREAD

**Issue by MathJud** [qaul/qaul.net#541]
The qaul daemon [qauld](https://github.com/qaul/qaul.net/tree/main/rust/clients/qauld) runs headless in the background. Create a second binary `qauld-ctl` To control it. For this you also need to setup a communication channel between `qauld` and `qauld-ctl` over which you can control qauld via the protobuf RPC.

- [x] Create a local communication channel for qauld which is only locally accessible (e.g. a unix socket)
- [x] Create a new `qauld-ctl` CLI binary that connects to `qauld`
- [x] Send protobuf messages from `qauld-ctl` to `qauld` and display the results in `qauld-ctl`
  - For how to use the protobuf RPC to control libqaul, check [qaul-cli](https://github.com/qaul/qaul.net/tree/main/rust/clients/cli)

**Comment by Jadhav-Dhanashri** [comment]
Hello maintainers,
I'm new to freifunk.net open source contributions excited to get started. I would like to work on this issue , & I'll follow the contribution guidelines carefully. Could you please Assign it to me if it's available?
Thank you!

**Comment by Lilit0x** [comment]
@MathJud 

Basically, we need a way to control running `qauld` instances programmatically. The current qaul-cli embeds libqaul directly and communicates via in-process channels, which is okay for a standalone client, but cannot control an already-running daemon.

The goal is two-fold:
1. Add a control interface to qauld (Unix socket)
2. Create `qauld-ctl` binary that connects to it

Primary use case: the e2e testing framework. Secondary: giving users a proper CLI to manage their daemon.

## Where Should The Scoket Be Located?

We can run multiple `qauld` instances on the same machine, and each needs its own socket. The earlier [GSoC attempt](#543) hardcoded `/tmp/qauld.sock`, which obviously breaks with multiple instances.

So, you suggested `/var/run/qauld/qauld.sock` with user-specific subdirectories, but that has permission issues for non-root users.

Here is what I suggest: we put the socket in the `pwd`, same place `qauld` already stores its logs, config file and the rest. Each instance runs from a different directory, so isolation is automatic.

```
/path/to/instance-1/
├── config.yaml
├── qauld.sock    # control socket
├── qauld.pid     # for process management
└── logs/

/path/to/instance-2/
├── config.yaml
├── qauld.sock    ← another different seperate socket
├── qauld.pid
└── logs/
```

qauld-ctl finds the socket by:
1. Explicit `--socket /path/to/qauld.sock`
2. Directory flag `--dir /path/to/instance` (looks for qauld.sock inside)
3. Current directory (default) - just run qauld-ctl from the instance folder
4. Environment variable `QAULD_SOCKET`

## Protocol

Reuse the existing protobuf RPC format. qauld already has all the message types defined, libqaul already knows how to handle them. The socket server just bridges between the socket and libqaul's internal RPC channels.

## qauld-ctl Modes

**Single-shot:**
```bash
qauld-ctl users list
qauld-ctl --json node info    # structured output for scripts
qauld-ctl chat send <group_id> "hello"
```

**Interactive:**
```bash
qauld-ctl -i
qauld> users list
qauld> exit
```

We're prioritising single-shot for now since that's what the testing framework needs.

## Windows Compatibility

So, on this, I checked, and Unix domain sockets work on Windows 10 (1803+) and Server 2019+, but that is if we use tokio's cross-platform abstraction, not the std::os::unix mod in std and since the tokio migration PR has been merged this makes it easier, I think.

Options:
1. **Unix sockets only** - require modern Windows, simpler code
2. **Unix sockets + TCP localhost fallback** - works everywhere, slightly more code
3. **TCP only** - simplest but less secure (any local process can connect)

I'm leaning toward opt 2. The socket server code is almsot identical for both transports, it will just have different listener types. TCP fallback handles older Windows.

```bash
# Default: Unix socket
qauld                              # listens on ./qauld.sock
qauld-ctl users list               # connects to ./qauld.sock

# TCP fallback
qauld --control-tcp 127.0.0.1:9900
qauld-ctl --tcp 127.0.0.1:9900 users list
```

## Questions

1. What'd you think about the working-directory socket location, or should we stick to your `/var/run/qauld/` approach?

2. For Windows: Unix sockets + TCP fallback, or we should just use option 1 and handle the cases later?

3. Output formats: I'm thinking plain text default + `--json` flag?

**Comment by MathJud** [comment]
@Lilit0x 

Thanks a lot for your analysis and reflections and concepts.

>     1. What'd you think about the working-directory socket location, or should we stick to your `/var/run/qauld/` approach?

I'm all in for that! I integrates really well on how we are doing things currently.
The generic linux standard solution in the `/var/run` directory would need additional linux system integration work, and can be done at a later time, once we are integrating into the linux distributions.

>     2. For Windows: Unix sockets + TCP fallback, or we should just use option 1 and handle the cases later?

I suggest we go with option 1 "Unix sockets only". a) It can run on modern windows. b) opening a TCP connection causes additional security risks. Which would be a potentially problematic fallback.

>     3. Output formats: I'm thinking plain text default + `--json` flag?

Sounds great!
