### ISSUE TITLE
Advanced MDNS Options

### ISSUE THREAD

**Issue by MathJud** [qaul/qaul.net#624]
- [ ] Make IPv6/IPv4  mdns sending configurable
- [ ] Develop dual MDNS stack (IPv4 & IPv6) 
- [ ] Auto-Detect which stacks are active
- [ ] Reduce chatty-ness of MDNS messages
